train_path = "/content/drive/MyDrive/Dense-Video-Captioning/data/training_data"
test_path = "/content/drive/MyDrive/Dense-Video-Captioning/data/testing_data/"
batch_size = 160#80#320
learning_rate = 0.0007
epochs = 150
latent_dim =256
num_encoder_tokens = 2560
num_decoder_tokens = 1500
time_steps_encoder = 20
max_probability = -1
save_model_path = '/content/drive/MyDrive/Dense-Video-Captioning/model_final_2'
validation_split = 0.15
max_length = 10
search_type = 'greedy'
